name: bsoung
favicon: null
layout_spectrum: 0.9822874548844993
typography_spectrum: 0.8206191472709179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.00693104974925518
  lightness: 0.1284187075216323
  saturation: 0.3778843351174146
  rhythmicContrast: 0.282245748443529
purpose: []
