name: bsoung
favicon: null
layout_spectrum: 0.9822874548844993
typography_spectrum: 0.8206191472709179
title: Welcome to my homepage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1620'
    - '#334e5f'
    - '#74b9c8'
    - '#5a7383'
    - '#bcd6dc'
  brandStrength: 0
  lightness: 0.1284187075216323
  saturation: 0.3778843351174146
  rhythmicContrast: 0.282245748443529
purpose: []
